from peewee import *
from os import getenv

BASE = 'nuvem'


if BASE == 'nuvem':
    db = PostgresqlDatabase(database=getenv('DATABASE', 'defaultdb'),
                            host=getenv('HOST', 'linkimovel-brain-ag.l.aivencloud.com'),
                            port=getenv('PORT', '21242'),
                            user=getenv('USER', 'avnadmin'),
                            password=getenv('PASSWORD', 'AVNS_FLSIPqCapJPjpvmSHTG'))
else:
    db = MySQLDatabase(database=getenv('DATABASE', 'roleta_tatisky'),
                            host=getenv('HOST', 'localhost'),
                            port=getenv('PORT', 3306),
                            user=getenv('USER', 'root'),
                            password=getenv('PASSWORD', 'brandt'))


OPTIONS = {1: (['+2 Min Calcinha \nTransparente',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima',
                '+2 Min Calcinha \nTransparente',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima',
                'Fica Pra \nPróxima'], 1),
           2: ([
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima'], 3),
           3: ([
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               'Fica Pra\n Próxima'], 7),
           4: ([
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+4 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima'], 12),
           5: ([
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               '+4 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+4 Min Calcinha \nTransparente'], 18),
           6: ([
               '+2 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+5 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+2 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+4 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima'], 25),
           7: ([
               '+2 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               '+5 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+2 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               'Fica Pra \nPróxima',
               '+4 Min Calcinha \nTransparente',
               '+5 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima'], 33),
           8: ([
               '+2 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               '+5 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+6 Min Calcinha \nTransparente',
               '+2 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+5 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima'], 42),
           9: ([
               '+2 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               '+5 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+6 Min Calcinha \nTransparente',
               '+2 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+5 Min Calcinha \nTransparente',
               '+6 Min Calcinha \nTransparente'], 52),
           10: ([
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               '+5 Min Calcinha \nTransparente',
               '+6 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+7 Min Calcinha \nTransparente',
               '+3 Min Calcinha \nTransparente',
               '+4 Min Calcinha \nTransparente',
               '+5 Min Calcinha \nTransparente',
               'Fica Pra \nPróxima',
               '+6 Min Calcinha \nTransparente',
               '+7 Min Calcinha \nTransparente'], 65)
           }
